### ISSUE TITLE
죄송합니다

### ISSUE THREAD

**Issue by avocad5** [gnlow/Ent2ml-DB#2]
한두달전 (정확히는 기억이 안나지만) 에
Ent2ml-DB에 스선경험이 있는 유저들의 조회수, 좋아요 등등의 순위가 저장되어있는걸 봤습니다.
그게 신기해서 data.json에 있는 정보를 유저이름만 복붙해서 엔트리이야기 게시판에 올렸습니다.

그때는 오픈소스 시스템인 깃허브에 올려진 DB니까
맘대로 퍼가도 된다고 생각했었는데
제 생각이 짧았습니다. gnlow (dark) 님께 허락도 맡지 않고 DB의 정보를 엔트리 커뮤니티에 올린건 잘못한것같아요.
정말 죄송합니다...

지금은 그 글이 삭제되어서 찾을수없는상태입니다.
앞으로는 절대 DB의 정보를 함부로 엔트리커뮤니티에 올리지 않겠습니다.
다시한번 죄송합니다.

**Comment by gnlow** [comment]
잉 괜찮아요 공유해도 상관없어요.
이슈를 늦게 봤네요
